### ISSUE TITLE
Can not tag example in scenario outline

### ISSUE THREAD

**Issue by mawaliya** [elchupanebrej/pytest-bdd#88]
pytest-bdd-ng = "~=2.0.0"
python_full_version = "3.10.6"
pytest==7.2.2
gherkin-official==24.1.0
plugins: metadata-3.0.0, bdd-6.1.1, bdd-html-0.1.14a0, snapshot-0.9.0, html-3.2.0, check-2.1.5

Tagging example like this doesn't work. Pytest doesn't collect it.
```
        @only
        Examples: Test
            | case | data_type | 
            | 1     | ASD            |

**Comment by elchupanebrej** [comment]
Please provide `pytest` and `gherkin-official` versions

**Comment by mawaliya** [comment]
> Please provide `pytest` and `gherkin-official` versions

added them 🙇‍♂️

**Comment by mawaliya** [comment]
also just want add, I was looking how to use it, so in pytest-bdd-ng-2.0.0 branch, I went to this test https://github.com/elchupanebrej/pytest-bdd-ng/blob/19f8e33c7390e6faca2f860d4ca61dec3df797eb/tests/feature/test_tags.py
and the test for tag for examples are not there.

**Comment by elchupanebrej** [comment]
Added End to end test for this case, and it works: 
https://github.com/elchupanebrej/pytest-bdd-ng/blob/default/Features/Scenario/Outline/Tags%20for%20Scenario%20Outlines%20examples.feature

**Comment by elchupanebrej** [comment]
Could you please prove that there is some Scenario Outline that consumes your Examples section parameters?

**Comment by mawaliya** [comment]
> Could you please prove that there is some Scenario Outline that consumes your Examples section parameters?

So I have this sort of feature file
```
@tag1
Feature: Test
    Feature description

    Background: Test background
        Given I have background
    
    Scenario Outline: Test outline
        Given I have <data_type> in scenario outline

        Examples: first
            | case | data_type | 
            | 1     | ASD           |

        @tag2
        Examples: second
            | case | data_type | 
            | 1     | QWE          |
```

When I run `pytest -m tag1 --collect-only` it will collect both of examples
When I run `pytest -m tag2 --collect-only`, it will collect 0 test

**Comment by mawaliya** [comment]
> Please provide `pytest` and `gherkin-official` versions

I have added plugins info as well

**Comment by elchupanebrej** [comment]
I have added another E2E test with your case:
https://github.com/elchupanebrej/pytest-bdd-ng/pull/91

I can't reproduce this behavior locally, let see what full test matrix will show

**Comment by elchupanebrej** [comment]
Please double-check if you have registered marks in pytest.ini: https://docs.pytest.org/en/7.1.x/how-to/mark.html#mark

**Comment by mawaliya** [comment]
> Please double-check if you have registered marks in pytest.ini: https://docs.pytest.org/en/7.1.x/how-to/mark.html#mark

yeah, I have registered the marks already while using strict markers. 
Hmm Is there any other information that I can check?

**Comment by elchupanebrej** [comment]
My last assumption is that the structure of your Gherkin document is broken somehow, maybe you could use some Gherkin linter to check if your Gherkin file is OK?

You also could check `ASTBuilderMixin` class at pytest-bdd-ng project, every raw example has to produce a separate Pickle;
Read more about pickles https://github.com/cucumber/gherkin
